version: "3.8"
services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.1-alpine
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144